import openai

# Set up OpenAI API credentials
openai.api_key = "YOUR_API_KEY"

def plagiarism_detector():
    # Prompt user to enter the large paragraph to check
    text = input("Enter the large paragraph to check for plagiarism: ")

    # Concatenate the text with a separator
    separator = " \n\n "
    text_with_separator = text + separator

    # Send a request to OpenAI's GPT-3 language model to determine if the text was generated by a machine learning model
    response = openai.Completion.create(
        engine="davinci",
        prompt=f"Is the following text generated by a machine learning model like ChatGPT?\n\n{text_with_separator}\n",
        max_tokens=1,
        n=1,
        stop=None,
        temperature=0.0
    )

    # Check the response and return the result
    is_generated = bool(int(response.choices[0].text.strip()))
    if is_generated:
        print("Plagiarism detected! The text was generated by a machine learning model.")
    else:
        print("No plagiarism detected. The text was likely written by a human.")

# Call the plagiarism detector function
plagiarism_detector()
